version: '3'

services:
  db:
    image: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DB: ${MYSQL_DB:-app}
      MYSQL_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${POSTGRES_USER:-app}
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev
    
  www:
    build: php
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
